---
- hosts: ec2-grafana-project
  become: true
  tasks:
  - name: Update package cache
    apt:
      update_cache: yes

  - name: Upgrade packages
    apt:
      upgrade: dist

  - name: Install required packages for Prometheus and Grafana
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - curl
      - gnupg2
      - software-properties-common

  - name: Add Prometheus APT repository
    apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
    register: prometheus_key_result

  - name: Add Prometheus APT repository
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present
      filename: grafana
    when: prometheus_key_result.changed

  - name: Install Prometheus
    apt:
      name: prometheus
      state: present

  - name: Install apt-transport-https package
    apt:
        name: apt-transport-https
        state: present

  - name: Add Grafana APT repository key
    apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

  - name: Add Grafana APT repository
    apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

  - name: Install Grafana
    apt:
        name: grafana
        state: present

  - name: Start and enable Grafana service
    systemd:
        name: grafana-server
        state: started
        enabled: true
